ssh_server:
  restart: always
  build: ssl-proxy
  ports:
    - 443:443
    - 80:80

  links:
    - sentry

redis:
  restart: always
  image: redis:3.2.6-alpine

postgres:
  restart: always
  image: postgres:9.2.19-alpine
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data

sentry:
  restart: always
  image: sentry:8.12.0
  environment:
    - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
  links:
    - redis
    - postgres
  volumes:
    - /var/lib/sentry/files:/var/lib/sentry/files

celery-beat:
  restart: always
  image: sentry:8.12.0
  environment:
    - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
  links:
    - redis
    - postgres
  volumes:
    - /var/lib/sentry/files:/var/lib/sentry/files
  command: sentry run cron

celery-worker:
  restart: always
  image: sentry:8.12.0
  environment:
    - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
  links:
    - redis
    - postgres
  volumes:
    - /var/lib/sentry/files:/var/lib/sentry/files
  command: sentry run worker

#inspired from:https://gist.github.com/puppybits/426319191bd4981cf6c8d9b6b06c6d46
#from https://gist.github.com/ebuildy/270f4ef3abd41e1490c1
#and https://forum.sentry.io/t/offline-sourcemaps-not-used/548
